### ISSUE TITLE
想问一下计算机视觉难不难啊

### ISSUE THREAD

**Issue by ghost** [HuangCongQing/UCAS_Course_2019#2]
我春季学期必须要选一门核心课，想问一下计算机视觉难不难，还有另一门机器学习师兄了解吗

**Comment by HuangCongQing** [comment]
不不好意思，回复晚了~！不知道你有没有计算机视觉的基础，如果没有的话，学的时候课下自己要多多自学，我当时疫情，期末考试是开卷考试，现在不知道期末考试如何。
